apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: inncw4fym-nodejs
  janus-idp.io/tekton: inncw4fym-nodejs
  backstage.io/kubernetes-id: inncw4fym-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: inncw4fym-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
